name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.5.3
        uses: actions/setup-python@v2
        with:
          python-version: '3.5.3'  # Debian Buster (stable)
      
      - name: Run Python unittests
        run: python3 -m unittest
